version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: prontoreserva-db-pg
    environment:
      - POSTGRES_PASSWORD=UmaSenhaForte!123
      - POSTGRES_DB=ProntoReservaDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ProntoReservaDB"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: prontoreserva-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=prontoreserva_user
      - RABBITMQ_DEFAULT_PASS=SenhaSegura123!
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: prontoreserva-api
    build: .
    ports:
      - "5129:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data:
